# Generated by Django 5.2 on 2025-05-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_auto_20210322_2234"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="tag",
            field=models.CharField(
                choices=[
                    ("learning", "Навчання"),
                    ("shopping", "Покупки"),
                    ("health", "Здоровʼя"),
                    ("sport", "Спорт"),
                ],
                default="learning",
                max_length=20,
            ),
        ),
    ]
